name: CI Storage

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download dependencies
        run: npm install

      - name: Verify project lint and try to fix it
        run: npm run lint:fix

      - name: Run the tests from project
        run: echo ${{ secrets.GCS_FILE_CONTENT }} | base64 -d > gcs-credentials.json && npm run test
        env:
          APP_NAME: SecJS
          APP_URL: https://cdn.secjs.io
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCS_ENDPOINT: ${{ secrets.GCS_ENDPOINT }}
          GCS_PROJECT: ${{ secrets.GCS_PROJECT }}
          GCS_SECRET: ${{ secrets.GCS_SECRET }}
